# Generated by Django 4.0.6 on 2022-07-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.BooleanField(db_index=True, null=True, verbose_name='Опубликовано')),
                ('model', models.CharField(blank=True, max_length=250, verbose_name='Модель')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, verbose_name='URL')),
                ('short_text', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание')),
                ('full_text', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/', verbose_name='Фото')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_editing', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['date_publication'],
            },
        ),
    ]
