# Generated by Django 4.0.5 on 2022-07-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uhod_base',
            options={'ordering': ['date_publication', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='categoryuhod',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Имя строки'),
        ),
        migrations.AddField(
            model_name='uhod_base',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Имя строки'),
        ),
        migrations.AlterField(
            model_name='uhod_base',
            name='category',
            field=models.ForeignKey(blank=True, max_length=250, on_delete=django.db.models.deletion.PROTECT, to='news.categoryuhod', verbose_name='Категория'),
        ),
    ]
