# Generated by Django 4.0.5 on 2022-07-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_uhod_base_options_alter_uhod_base_date_editing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.ImageField(upload_to='', verbose_name='Номер')),
                ('list_json', models.JSONField(verbose_name='Json')),
            ],
        ),
    ]
