# Generated by Django 4.0.5 on 2022-07-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_testjson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testjson',
            options={'verbose_name': 'Json', 'verbose_name_plural': 'Json'},
        ),
        migrations.AlterField(
            model_name='testjson',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
