# Generated by Django 4.0.5 on 2022-06-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_base',
            name='a1',
            field=models.BooleanField(null=True, verbose_name='a1'),
        ),
        migrations.AddField(
            model_name='table_base',
            name='a2',
            field=models.DateTimeField(auto_now=True, verbose_name='a1'),
        ),
    ]
