# Generated by Django 4.0.5 on 2022-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table_base_a1_table_base_a2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_base',
            name='a2',
            field=models.DateTimeField(auto_now=True, verbose_name='a2'),
        ),
    ]
