# Generated by Django 4.0.5 on 2022-06-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_table_base_a2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_base_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=250, verbose_name='State')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('all_res', models.CharField(max_length=250, verbose_name='All_res')),
                ('aaa', models.BooleanField(null=True, verbose_name='aaa')),
                ('bbb', models.DateTimeField(auto_now_add=True, verbose_name='bbb')),
                ('ccc', models.DateTimeField(auto_now=True, verbose_name='ccc')),
                ('ddd', models.DateTimeField(blank=True, verbose_name='ddd')),
                ('iii', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='iii')),
                ('fff', models.EmailField(max_length=254, verbose_name='fff')),
                ('ggg', models.IntegerField(verbose_name='ggg')),
                ('hhh', models.TextField(max_length=254, verbose_name='hhh')),
            ],
            options={
                'verbose_name': 'БотДВА',
                'verbose_name_plural': 'БотыДВА',
            },
        ),
        migrations.AlterField(
            model_name='table_base',
            name='a2',
            field=models.DateTimeField(auto_now_add=True, verbose_name='a2'),
        ),
    ]
