# Generated by Django 4.0.5 on 2022-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_table_base_two_alter_table_base_a2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_base_three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eee', models.ImageField(height_field=True, upload_to='photo/%Y/%m/%d/', width_field=True)),
            ],
            options={
                'verbose_name': 'БотТРИ',
                'verbose_name_plural': 'БотыТРИ',
            },
        ),
    ]
