# Generated by Django 4.0.5 on 2022-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_alter_table_base_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_base_three',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
