# Generated by Django 4.0.5 on 2022-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_table_base_three_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_base_three',
            name='eee',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
    ]
