# Generated by Django 4.0.5 on 2022-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_table_base_three_eee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_input_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=250, verbose_name='Text input')),
            ],
        ),
    ]
